# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoastlineBuilder
                                 A QGIS plugin
 Builds coastlines of a river according to water surface slope
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-27
        copyright            : (C) 2022 by Kirill Kotelevsky
        email                : yixwellet@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoastlineBuilder class from file CoastlineBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coastline_builder import CoastlineBuilder
    return CoastlineBuilder(iface)
